export const products = [
  {
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    name: 'Thunderbird',
    price: 124,
    salePrice: 104,
    onSale: false,
    image: 'car.jpg',
    categories: ['Ford'],
  },
  {
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    name: 'NSX',
    price: 196,
    salePrice: 176,
    onSale: true,
    image: 'car.jpg',
    categories: ['Acura'],
  },
  {
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    name: 'Alcyone SVX',
    price: 120,
    salePrice: 100,
    onSale: false,
    image: 'car.jpg',
    categories: ['Subaru'],
  },
  {
    description:
      'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    name: 'Explorer',
    price: 167,
    salePrice: 147,
    onSale: true,
    image: 'car.jpg',
    categories: ['Ford'],
  },
  {
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    name: 'Suburban 1500',
    price: 191,
    salePrice: 171,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    name: 'Cobalt SS',
    price: 166,
    salePrice: 146,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    name: 'Suburban 2500',
    price: 173,
    salePrice: 153,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    name: 'Riviera',
    price: 143,
    salePrice: 123,
    onSale: false,
    image: 'car.jpg',
    categories: ['Buick'],
  },
  {
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    name: 'E-Series',
    price: 144,
    salePrice: 124,
    onSale: false,
    image: 'car.jpg',
    categories: ['Ford'],
  },
  {
    description:
      'Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    name: 'Pilot',
    price: 197,
    salePrice: 177,
    onSale: true,
    image: 'car.jpg',
    categories: ['Honda'],
  },
  {
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    name: '430 Scuderia',
    price: 177,
    salePrice: 157,
    onSale: false,
    image: 'car.jpg',
    categories: ['Ferrari'],
  },
  {
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    name: 'Express 3500',
    price: 140,
    salePrice: 120,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    name: 'del Sol',
    price: 154,
    salePrice: 134,
    onSale: true,
    image: 'car.jpg',
    categories: ['Honda'],
  },
  {
    description: 'Fusce consequat. Nulla nisl. Nunc nisl.',
    name: 'Mustang',
    price: 137,
    salePrice: 117,
    onSale: false,
    image: 'car.jpg',
    categories: ['Ford'],
  },
  {
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    name: 'Suburban 2500',
    price: 169,
    salePrice: 149,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    name: 'LeMans',
    price: 178,
    salePrice: 158,
    onSale: true,
    image: 'car.jpg',
    categories: ['Pontiac'],
  },
  {
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    name: 'QX',
    price: 104,
    salePrice: 84,
    onSale: false,
    image: 'car.jpg',
    categories: ['Infiniti'],
  },
  {
    description:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    name: 'Sidekick',
    price: 180,
    salePrice: 160,
    onSale: false,
    image: 'car.jpg',
    categories: ['Suzuki'],
  },
  {
    description:
      'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    name: 'M3',
    price: 116,
    salePrice: 96,
    onSale: true,
    image: 'car.jpg',
    categories: ['BMW'],
  },
  {
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    name: 'S10',
    price: 170,
    salePrice: 150,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    name: 'XJ Series',
    price: 131,
    salePrice: 111,
    onSale: true,
    image: 'car.jpg',
    categories: ['Jaguar'],
  },
  {
    description:
      'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    name: 'Jimmy',
    price: 132,
    salePrice: 112,
    onSale: true,
    image: 'car.jpg',
    categories: ['GMC'],
  },
  {
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
    name: '944',
    price: 147,
    salePrice: 127,
    onSale: false,
    image: 'car.jpg',
    categories: ['Porsche'],
  },
  {
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    name: 'Villager',
    price: 185,
    salePrice: 165,
    onSale: false,
    image: 'car.jpg',
    categories: ['Mercury'],
  },
  {
    description:
      'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    name: 'Mustang',
    price: 152,
    salePrice: 132,
    onSale: false,
    image: 'car.jpg',
    categories: ['Ford'],
  },
  {
    description:
      'Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    name: 'Cavalier',
    price: 115,
    salePrice: 95,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    name: 'Express 1500',
    price: 121,
    salePrice: 101,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    name: 'G5',
    price: 101,
    salePrice: 81,
    onSale: true,
    image: 'car.jpg',
    categories: ['Pontiac'],
  },
  {
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    name: 'Elantra',
    price: 157,
    salePrice: 137,
    onSale: false,
    image: 'car.jpg',
    categories: ['Hyundai'],
  },
  {
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    name: 'Millenia',
    price: 183,
    salePrice: 163,
    onSale: false,
    image: 'car.jpg',
    categories: ['Mazda'],
  },
  {
    description:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    name: 'Trans Sport',
    price: 193,
    salePrice: 173,
    onSale: true,
    image: 'car.jpg',
    categories: ['Pontiac'],
  },
  {
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    name: 'Monte Carlo',
    price: 171,
    salePrice: 151,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    name: 'S40',
    price: 119,
    salePrice: 99,
    onSale: true,
    image: 'car.jpg',
    categories: ['Volvo'],
  },
  {
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
    name: 'Legacy',
    price: 168,
    salePrice: 148,
    onSale: true,
    image: 'car.jpg',
    categories: ['Subaru'],
  },
  {
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
    name: 'Talon',
    price: 123,
    salePrice: 103,
    onSale: true,
    image: 'car.jpg',
    categories: ['Eagle'],
  },
  {
    description: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    name: 'Odyssey',
    price: 187,
    salePrice: 167,
    onSale: false,
    image: 'car.jpg',
    categories: ['Honda'],
  },
  {
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    name: '7 Series',
    price: 186,
    salePrice: 166,
    onSale: false,
    image: 'car.jpg',
    categories: ['BMW'],
  },
  {
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    name: 'LeBaron',
    price: 177,
    salePrice: 157,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chrysler'],
  },
  {
    description: 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    name: 'Protege',
    price: 157,
    salePrice: 137,
    onSale: false,
    image: 'car.jpg',
    categories: ['Mazda'],
  },
  {
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    name: 'Passat',
    price: 130,
    salePrice: 110,
    onSale: false,
    image: 'car.jpg',
    categories: ['Volkswagen'],
  },
  {
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    name: 'Continental',
    price: 160,
    salePrice: 140,
    onSale: true,
    image: 'car.jpg',
    categories: ['Lincoln'],
  },
  {
    description:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    name: 'Grand Cherokee',
    price: 154,
    salePrice: 134,
    onSale: true,
    image: 'car.jpg',
    categories: ['Jeep'],
  },
  {
    description: 'Fusce consequat. Nulla nisl. Nunc nisl.',
    name: '228',
    price: 174,
    salePrice: 154,
    onSale: true,
    image: 'car.jpg',
    categories: ['Maserati'],
  },
  {
    description:
      'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    name: 'LR4',
    price: 195,
    salePrice: 175,
    onSale: true,
    image: 'car.jpg',
    categories: ['Land Rover'],
  },
  {
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    name: 'G',
    price: 190,
    salePrice: 170,
    onSale: false,
    image: 'car.jpg',
    categories: ['Infiniti'],
  },
  {
    description: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    name: 'QX',
    price: 178,
    salePrice: 158,
    onSale: true,
    image: 'car.jpg',
    categories: ['Infiniti'],
  },
  {
    description:
      'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    name: 'Ascender',
    price: 125,
    salePrice: 105,
    onSale: false,
    image: 'car.jpg',
    categories: ['Isuzu'],
  },
  {
    description:
      'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    name: 'Touareg 2',
    price: 171,
    salePrice: 151,
    onSale: false,
    image: 'car.jpg',
    categories: ['Volkswagen'],
  },
  {
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    name: 'Titan',
    price: 188,
    salePrice: 168,
    onSale: false,
    image: 'car.jpg',
    categories: ['Nissan'],
  },
  {
    description:
      'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    name: 'CX-9',
    price: 121,
    salePrice: 101,
    onSale: true,
    image: 'car.jpg',
    categories: ['Mazda'],
  },
  {
    description:
      'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    name: 'Capri',
    price: 178,
    salePrice: 158,
    onSale: true,
    image: 'car.jpg',
    categories: ['Mercury'],
  },
  {
    description:
      'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    name: '323',
    price: 163,
    salePrice: 143,
    onSale: false,
    image: 'car.jpg',
    categories: ['Mazda'],
  },
  {
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    name: 'Electra',
    price: 124,
    salePrice: 104,
    onSale: false,
    image: 'car.jpg',
    categories: ['Buick'],
  },
  {
    description:
      'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    name: 'C-Class',
    price: 190,
    salePrice: 170,
    onSale: true,
    image: 'car.jpg',
    categories: ['Mercedes-Benz'],
  },
  {
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    name: 'Suburban 1500',
    price: 192,
    salePrice: 172,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    name: 'Camaro',
    price: 127,
    salePrice: 107,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    name: 'Express 3500',
    price: 165,
    salePrice: 145,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    name: 'Silverado 3500',
    price: 130,
    salePrice: 110,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    name: 'Sephia',
    price: 177,
    salePrice: 157,
    onSale: true,
    image: 'car.jpg',
    categories: ['Kia'],
  },
  {
    description:
      'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    name: 'Range Rover',
    price: 189,
    salePrice: 169,
    onSale: true,
    image: 'car.jpg',
    categories: ['Land Rover'],
  },
  {
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    name: 'Metro',
    price: 117,
    salePrice: 97,
    onSale: false,
    image: 'car.jpg',
    categories: ['Geo'],
  },
  {
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    name: 'Town & Country',
    price: 164,
    salePrice: 144,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chrysler'],
  },
  {
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    name: 'SL-Class',
    price: 136,
    salePrice: 116,
    onSale: true,
    image: 'car.jpg',
    categories: ['Mercedes-Benz'],
  },
  {
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    name: 'Tiburon',
    price: 164,
    salePrice: 144,
    onSale: true,
    image: 'car.jpg',
    categories: ['Hyundai'],
  },
  {
    description:
      'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    name: 'Santa Fe',
    price: 123,
    salePrice: 103,
    onSale: true,
    image: 'car.jpg',
    categories: ['Hyundai'],
  },
  {
    description:
      'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    name: 'Volt',
    price: 153,
    salePrice: 133,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    name: 'Roadrunner',
    price: 149,
    salePrice: 129,
    onSale: true,
    image: 'car.jpg',
    categories: ['Plymouth'],
  },
  {
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    name: 'Montero',
    price: 171,
    salePrice: 151,
    onSale: true,
    image: 'car.jpg',
    categories: ['Mitsubishi'],
  },
  {
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    name: 'Prizm',
    price: 189,
    salePrice: 169,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    name: 'MPV',
    price: 185,
    salePrice: 165,
    onSale: true,
    image: 'car.jpg',
    categories: ['Mazda'],
  },
  {
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    name: 'SRX',
    price: 182,
    salePrice: 162,
    onSale: false,
    image: 'car.jpg',
    categories: ['Cadillac'],
  },
  {
    description: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    name: '7 Series',
    price: 122,
    salePrice: 102,
    onSale: false,
    image: 'car.jpg',
    categories: ['BMW'],
  },
  {
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    name: 'Tracer',
    price: 193,
    salePrice: 173,
    onSale: true,
    image: 'car.jpg',
    categories: ['Mercury'],
  },
  {
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    name: 'F450',
    price: 110,
    salePrice: 90,
    onSale: false,
    image: 'car.jpg',
    categories: ['Ford'],
  },
  {
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    name: 'Silverado 3500',
    price: 135,
    salePrice: 115,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    name: 'Paseo',
    price: 191,
    salePrice: 171,
    onSale: true,
    image: 'car.jpg',
    categories: ['Toyota'],
  },
  {
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    name: 'Liberty',
    price: 182,
    salePrice: 162,
    onSale: true,
    image: 'car.jpg',
    categories: ['Jeep'],
  },
  {
    description: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    name: 'Sierra 2500',
    price: 190,
    salePrice: 170,
    onSale: true,
    image: 'car.jpg',
    categories: ['GMC'],
  },
  {
    description:
      'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    name: 'Corolla',
    price: 170,
    salePrice: 150,
    onSale: true,
    image: 'car.jpg',
    categories: ['Toyota'],
  },
  {
    description:
      'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    name: '57',
    price: 146,
    salePrice: 126,
    onSale: true,
    image: 'car.jpg',
    categories: ['Maybach'],
  },
  {
    description:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    name: 'Excel',
    price: 149,
    salePrice: 129,
    onSale: false,
    image: 'car.jpg',
    categories: ['Mitsubishi'],
  },
  {
    description:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    name: 'Phaeton',
    price: 177,
    salePrice: 157,
    onSale: false,
    image: 'car.jpg',
    categories: ['Volkswagen'],
  },
  {
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    name: 'Grand Am',
    price: 103,
    salePrice: 83,
    onSale: true,
    image: 'car.jpg',
    categories: ['Pontiac'],
  },
  {
    description: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    name: 'X6',
    price: 112,
    salePrice: 92,
    onSale: false,
    image: 'car.jpg',
    categories: ['BMW'],
  },
  {
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    name: 'A4',
    price: 106,
    salePrice: 86,
    onSale: true,
    image: 'car.jpg',
    categories: ['Audi'],
  },
  {
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    name: 'del Sol',
    price: 196,
    salePrice: 176,
    onSale: true,
    image: 'car.jpg',
    categories: ['Honda'],
  },
  {
    description:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    name: 'Passat',
    price: 140,
    salePrice: 120,
    onSale: false,
    image: 'car.jpg',
    categories: ['Volkswagen'],
  },
  {
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    name: 'Altima',
    price: 173,
    salePrice: 153,
    onSale: false,
    image: 'car.jpg',
    categories: ['Nissan'],
  },
  {
    description:
      'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    name: 'RX-7',
    price: 154,
    salePrice: 134,
    onSale: false,
    image: 'car.jpg',
    categories: ['Mazda'],
  },
  {
    description:
      'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    name: 'Escalade EXT',
    price: 114,
    salePrice: 94,
    onSale: false,
    image: 'car.jpg',
    categories: ['Cadillac'],
  },
  {
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    name: 'CX',
    price: 200,
    salePrice: 180,
    onSale: true,
    image: 'car.jpg',
    categories: ['Citroën'],
  },
  {
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    name: 'Sportage',
    price: 138,
    salePrice: 118,
    onSale: true,
    image: 'car.jpg',
    categories: ['Kia'],
  },
  {
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    name: 'Suburban 1500',
    price: 136,
    salePrice: 116,
    onSale: true,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    name: 'F350',
    price: 173,
    salePrice: 153,
    onSale: true,
    image: 'car.jpg',
    categories: ['Ford'],
  },
  {
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
    name: 'Optima',
    price: 194,
    salePrice: 174,
    onSale: false,
    image: 'car.jpg',
    categories: ['Kia'],
  },
  {
    description:
      'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    name: 'Voyager',
    price: 176,
    salePrice: 156,
    onSale: true,
    image: 'car.jpg',
    categories: ['Plymouth'],
  },
  {
    description: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    name: 'TrailBlazer',
    price: 104,
    salePrice: 84,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
  {
    description:
      'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    name: 'Santa Fe',
    price: 125,
    salePrice: 105,
    onSale: true,
    image: 'car.jpg',
    categories: ['Hyundai'],
  },
  {
    description:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    name: 'RSX',
    price: 104,
    salePrice: 84,
    onSale: false,
    image: 'car.jpg',
    categories: ['Acura'],
  },
  {
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.',
    name: 'Avalanche',
    price: 161,
    salePrice: 141,
    onSale: false,
    image: 'car.jpg',
    categories: ['Chevrolet'],
  },
];
